name: Check ACM Certificate Expiry

on:
  schedule:
    - cron: '0 8 * * *'  # Minden nap 08:00 UTC (pl. 9:00 CET)
  workflow_dispatch:      # Manuális indítás lehetősége

jobs:
  check-expiry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check ACM certificate expiry dates
        run: |
          echo "🔍 Checking ACM certificates in us-east-1..."
          aws acm list-certificates --region us-east-1 --query "CertificateSummaryList[*].CertificateArn" --output text | while read ARN; do
            EXPIRY=$(aws acm describe-certificate --region us-east-1 --certificate-arn $ARN --query "Certificate.NotAfter" --output text)
            DOMAIN=$(aws acm describe-certificate --region us-east-1 --certificate-arn $ARN --query "Certificate.DomainName" --output text)
            DAYS_LEFT=$(( ( $(date -d "$EXPIRY" +%s) - $(date +%s) ) / 86400 ))

            if [ $DAYS_LEFT -le 30 ]; then
              echo "⚠️  $DOMAIN expires in $DAYS_LEFT days on $EXPIRY"
            else
              echo "✅ $DOMAIN is valid for $DAYS_LEFT more days (expires $EXPIRY)"
            fi
          done
